### ISSUE TITLE
Quality checks unclear

### ISSUE THREAD

**Issue by j0sien** [asreview/paper-megameta-postprocessing-screeningresults#41]
While reading your impressive documentation, it remains unclear to me what you did in step 4 of the post-processing, 'Deal with noisy labels corrected in two rounds of quality checks'.
I cannot find a script with a similar name or an explanation.
Could you point me to where it is, or if not add it to the documentation?

**Comment by j0sien** [comment]
Hi Rens.
One more question on this point.
In the quality check 1, did you check only the unlabeled irrelevant records?
or also the ones that were already labeled by a human as irrelevant?

**Comment by Rensvandeschoot** [comment]
We checked the records labeled irrelevant in the 2 screening rounds. We selected those records in the dataset and deleted all others. Then, we removed the labels (otherwise ASReview will mark the records for training data) and added 2x 20 records for prior knowledge. The original records labeled irrelevant can then be checked for relevance again.

hope this helps!

**Comment by j0sien** [comment]
Thanks @Rensvandeschoot . Just a double check: you have not checked the unlabeled records?

**Comment by Rensvandeschoot** [comment]
We have applied two screening rounds for checking the unlabelled records and we stopped inspecting more records after reaching our pre-defined stopping rules :-)
